### ISSUE TITLE
Support true color (ISO-8613-3)

### ISSUE THREAD

**Issue by nnmet** [chalk/slice-ansi#17]
One way to [do](https://github.com/chalk/slice-ansi/blob/master/index.js#L33) it:
```js
const code = /\[(.*?)m/.exec(str.slice(i))[1]
```
I can't quite get the test cases, the output seems ok, but a lot of garbage tags e.g.:
```js
test('supports true color (ISO-8613-3)', t => {
  t.is(m(
    '\u001b[38;5;181mpretty \u001b[39m\u001b[38;5;181municorn\u001b[39m', 7, 14),
    '\u001b[38;5;181municorn\u001b[39m'
  )
  // == '\u001b[38;5;181m\u001b[39m\u001b[38;5;181municorn\u001b[39m'
})
```

**Comment by piranna** [comment]
I have done a fix for that at https://github.com/chalk/slice-ansi/pull/18. Regarding the garbage tags, it's due how `slice-ansi` works, because it doesn't maintain state, just only the last tag for the current color. By maintaining state, it could be able to remove the useless and closed ones, maybe could be done in another pull-request.
